- name: Install 7zip on Hosts
  hosts: all
  vars:
    ansible_remote_tmp: C:\Windows\Temp
  collections:
  - chocolatey.chocolatey
  tasks:
    - name: Install 7zip
      chocolatey.chocolatey.win_chocolatey:
        name: 7zip
        state: present
